name: escala_adventista
description: "O Escala Adventista é uma ferramenta que auxilia na organização das atividades da igreja, distribuindo tarefas e gerenciando escalas de forma transparente e prática. Com uma interface intuitiva, permite que os usuários acessem facilmente suas responsabilidades e consultem as escalas das diversas funções semanais."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.15.0
  go_router: ^14.3.0
  dio:
  pretty_dio_logger:
  get_it:
  shared_preferences:
  flutter_svg: ^1.1.6
  bloc:
  flutter_bloc:
  equatable: ^2.0.5
  dartz: ^0.10.1

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test:

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/svgs/logo_7.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
