name: escala_adventista
description: "O Escala Adventista é uma ferramenta que auxilia na organização das atividades da igreja, distribuindo tarefas e gerenciando escalas de forma transparente e prática. Com uma interface intuitiva, permite que os usuários acessem facilmente suas responsabilidades e consultem as escalas das diversas funções semanais."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  design_system:
    path: ./design_system
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.4.0
  cloud_firestore: ^4.15.0
  go_router: ^14.3.0
  dio:
  pretty_dio_logger:
  get_it:
  shared_preferences:
  flutter_svg: ^1.1.6
  bloc:
  flutter_bloc:
  equatable: ^2.0.5
  dartz: ^0.10.1
  uicons: ^1.0.1
  connectivity_plus: ^5.0.2
  package_info_plus: ^8.1.1
  flutter_localizations:
    sdk: flutter
  yaml: ^3.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test:

flutter:

  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/images/svg/
    - .env