name: design_system
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^6.2.1
  uicons: ^1.0.1
  get_it: ^7.6.7
  bloc: ^8.1.1
  escala_adventista:
    path: ../
  flutter_bloc: ^8.1.6
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/images/svg/
    - assets/images/
